### ISSUE TITLE
Bug: `process.exit(code)` always exits with zero exit code

### ISSUE THREAD

**Issue by tengyifei** [atom/electron#1983]
In Electron main process:
```js
process.exit(1);
```

In shell
```bash
> electron .
> echo $?
0
```
Electron version: 0.27.3
Doesn't happen in Node.

**Comment by paulcbetts** [comment]
You need to use `app.quit` to exit Electron apps, process.exit will cause Weird Things™ to happen

**Comment by tengyifei** [comment]
Well it was suggested in https://github.com/atom/electron/issues/1944

**Comment by paulcbetts** [comment]
Huh. Well then. Um. I think we should fix `app.quit`

**Comment by deepak1556** [comment]
Seems to be working fine on OSX(10.9.5) with master branch.

**Comment by DepthDeluxe** [comment]
Looks like it's because `app.quit` calls a browser API close which isn't handled with `process.exit()`.  Since the process API is part of Node, there may need to be a redefinition of that function...

https://github.com/atom/electron/blob/02bdace366f38271b5c186412f42810ecb06e99e/atom/browser/api/atom_api_app.cc#L222

**Comment by deepak1556** [comment]
update `process.exit` on linux causes crash with the following trace

```
hello-atom git:master ✗ ✩  ❯ ../atom-shell/out/D/electron ./dialog-app                                                                                                                      ⏎
[4441:0622/090327:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
                                                                                                                                                                                              
hello-atom git:master ✗ ✩  ❯ [4458:0622/090327:WARNING:ipc_message_attachment_set.cc(37)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
[4464:0622/090327:INFO:renderer_main.cc(200)] Renderer process started
[4464:0622/090327:WARNING:ipc_message_attachment_set.cc(37)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
Received signal 11 SEGV_MAPERR 000000000208
#0 0x7fb45e46aca8 <unknown>
#1 0x7fb456e83740 <unknown>
#2 0x7fb468b489c3 uv__async_send
#3 0x7fb468b48954 uv_async_send
#4 0x0000006da78c atom::NodeBindings::WakeupEmbedThread()
#5 0x0000006da6f8 atom::NodeBindings::~NodeBindings()
#6 0x0000006dd505 atom::NodeBindingsLinux::~NodeBindingsLinux()
#7 0x0000006dd529 atom::NodeBindingsLinux::~NodeBindingsLinux()
#8 0x000000693012 base::DefaultDeleter<>::operator()()
#9 0x000000692fc0 base::internal::scoped_ptr_impl<>::~scoped_ptr_impl()
#10 0x000000692145 scoped_ptr<>::~scoped_ptr()
#11 0x0000006e82a8 atom::AtomRendererClient::~AtomRendererClient()
#12 0x0000006e8319 atom::AtomRendererClient::~AtomRendererClient()
#13 0x00000068de32 base::DefaultDeleter<>::operator()()
#14 0x00000068e310 base::internal::scoped_ptr_impl<>::~scoped_ptr_impl()
#15 0x00000068d8c5 scoped_ptr<>::~scoped_ptr()
#16 0x00000068d13a atom::AtomMainDelegate::~AtomMainDelegate()
#17 0x00000068bfa7 main
#18 0x7fb452c24800 __libc_start_main
#19 0x00000068bdd9 _start
  r8: 000006f1b9f2b000  r9: 0000000000000000 r10: 0000000000000937 r11: 00007fb468b489a0
 r12: 000000000068bdb0 r13: 00007fffcc3c8f40 r14: 0000000000000000 r15: 0000000000000000
  di: 00000000000001c8  si: 0000000000000000  bp: 00007fffcc3c8b70  bx: 0000000000000000
  dx: 0000000000000001  ax: 00000000000001c8  cx: 0000000000000000  sp: 00007fffcc3c8b40
  ip: 00007fb468b489c3 efl: 0000000000010202 cgf: 0000000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000208
[4463:0622/090327:INFO:renderer_main.cc(200)] Renderer process started
[4463:0622/090327:WARNING:ipc_message_attachment_set.cc(37)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
Received signal 11 SEGV_MAPERR 000000000208
#0 0x7f56b07f8ca8 <unknown>
#1 0x7f56a9211740 <unknown>
#2 0x7f56baed69c3 uv__async_send
#3 0x7f56baed6954 uv_async_send
#4 0x0000006da78c atom::NodeBindings::WakeupEmbedThread()
#5 0x0000006da6f8 atom::NodeBindings::~NodeBindings()
#6 0x0000006dd505 atom::NodeBindingsLinux::~NodeBindingsLinux()
#7 0x0000006dd529 atom::NodeBindingsLinux::~NodeBindingsLinux()
#8 0x000000693012 base::DefaultDeleter<>::operator()()
#9 0x000000692fc0 base::internal::scoped_ptr_impl<>::~scoped_ptr_impl()
#10 0x000000692145 scoped_ptr<>::~scoped_ptr()
#11 0x0000006e82a8 atom::AtomRendererClient::~AtomRendererClient()
#12 0x0000006e8319 atom::AtomRendererClient::~AtomRendererClient()
#13 0x00000068de32 base::DefaultDeleter<>::operator()()
#14 0x00000068e310 base::internal::scoped_ptr_impl<>::~scoped_ptr_impl()
#15 0x00000068d8c5 scoped_ptr<>::~scoped_ptr()
#16 0x00000068d13a atom::AtomMainDelegate::~AtomMainDelegate()
#17 0x00000068bfa7 main
#18 0x7f56a4fb2800 __libc_start_main
#19 0x00000068bdd9 _start
  r8: 000033371c864000  r9: 0000000000000000 r10: 0000000000000937 r11: 00007f56baed69a0
 r12: 000000000068bdb0 r13: 00007ffc4a8e91a0 r14: 0000000000000000 r15: 0000000000000000
  di: 00000000000001c8  si: 0000000000000000  bp: 00007ffc4a8e8dd0  bx: 0000000000000000
  dx: 0000000000000001  ax: 00000000000001c8  cx: 0000000000000000  sp: 00007ffc4a8e8da0
  ip: 00007f56baed69c3 efl: 0000000000010206 cgf: 0000000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000208

```

**Comment by deepak1556** [comment]
**update** Works fine on linux, unable to reproduce the crash anymore. Sorry for the confusion, must have been something i messed up with the code.

**Comment by jprichardson** [comment]
Confirmed on Mac OS X 10.10.3 / Electron 0.29.2. I was sure that I was doing something wrong... but, yeah it seems reasonable that `app.quit` should accept an exit code parameter.

**Comment by jprichardson** [comment]
Any update on this?

**Comment by zcbenz** [comment]
I just tested in v0.33.0 and it works as expected, seems that it has been fixed as part of Node.js or Chrome update.

**Comment by mkozakov** [comment]
I'm running version ```0.33.3``` and I'm still getting an exit code of 0 after running ```process.exit(1)```

**Comment by jaredly** [comment]
`process.exit(code)` is working in `0.35.2`
