### PR TITLE
Update to node v4.1.0

### LINKED ISSUE #2755: vm.createContext crash on 0.32.x
**Electron Version:** 0.32.1
**System:** OS X 10.9.5

electron

### LINKED ISSUE #2799: Cannot use `setImmediate` in child process
Calling `setImmediate` in a child process spawned with [`fork`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) fails with the following: 

```
TypeError: process.activateUvLoop is not a function
    at setImmediate (node.js:18:13)
    at process.<anonymous> (/Users/pgoyal/Work/Test/electron-test/child.js:2:3)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:632:10)
    at Pipe.channel.onread (internal/child_process.js:421:11)
```

Tested on OSX with [v0.32.3](https://github.com/atom/electron/releases/tag/v0.32.3). Works fine with < v0.32.2.

[Here is a small sample](https://gist.github.com/sapandiwakar/0b6ad79dc5ae5cbcf9a7) to reproduce the issue.

### PR DESCRIPTION
**Pull request by zcbenz**
Fixes #2755, also contains [a patch](https://github.com/atom/node/commit/aa9c7a2316ba7762f1d04d091585695be3e6be22) that fixes #2799.

### CODE REVIEW

**Comment by tomashanacek** [comment]
:+1:
