### ISSUE TITLE
Unable to start electron on windows

### ISSUE THREAD

**Issue by marsinvasion** [atom/electron#3181]
I'm having this problem on windows. It works fine on mac

I'm using electron packager with electron v0.34.0

Error: Cannot find module 'C:\Users\u\vm\win32-x64\resources\atom.asar\browser\lib\init.js'

**Comment by zcbenz** [comment]
Does the default app work? If the problem only happens after you packaged the app, you probably want to report this to https://github.com/maxogden/electron-packager.

**Comment by marsinvasion** [comment]
The packaged mac app works. The default app works as well as all it does is load a url.

There was a similar issue https://github.com/atom/electron/issues/2803 a month ago

Any particular reason you think this is not an electron issue but an electron-packager issue?

**Comment by zcbenz** [comment]
> Any particular reason you think this is not an electron issue but an electron-packager issue?

Because the way default app works is exactly the same with packaged app, so if default app works then under most cases Electron is working fine. Before you report this to electron-packager you can probably package the app manually to verify whether it is an issue of Electron.

**Comment by rbartholomay** [comment]
Did your app "spawn" the init.js script? I have a similar problem. With newer electron builds it seems not possible to spawn a script inside an asar package on windows

**Comment by marsinvasion** [comment]
I found a workaround where I replaced app.asar with the actual app folder. Now it runs without any problems.

**Comment by jviotti** [comment]
I'm having the exact same issue in Ubuntu on an application that runs fine on both OS X and Windows, and *does not* make use of `electron-packager`.

```sh
module.js:338 Uncaught Error: Cannot find module '/home/jviotti/Projects/herostratus/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/lib/init.js'
```

The file electron complains about does exist here:

```sh
$ asar list node_modules/electron-prebuilt/dist/resources/atom.asar | grep init.js
/browser/lib/init.js
/common/lib/init.js
/renderer/lib/init.js
```
@marsinvasion 

> I found the same workaround where I replaced app.asar with the actual app folder. Now it runs without any problems.

Can you explain the workaround in more detail?

**Comment by jviotti** [comment]
You can reproduce with:

```sh
git clone https://github.com/resin-io/herostratus
cd herostratus
npm install && bower install
npm start
```

**Comment by rbartholomay** [comment]
@jviotti i think that @marsinvasion removes the complete asar and use the original source code. In my opinion thats not a solution.
It runs fine with older electron build (with io.js)...   But with the newer build it seems there is no solution.

**Comment by jviotti** [comment]
@rbartholomay Do you have information about a specific Electron build version that doesn't have this problem?

**Comment by rbartholomay** [comment]
i am running the 0.32.3 build here...

**Comment by jviotti** [comment]
@rbartholomay Weird. I've been trying many older versions without success. The app *does* run in another computer running the same Ubuntu version.

@zcbenz Any chance we can re-open this issue?

**Comment by jviotti** [comment]
Update: Works fine in v0.25.3. I'll try to identify the first problematic version.

**Comment by jviotti** [comment]
It works up to v0.31.2, and starts failing in v0.32.0.

**Comment by rbartholomay** [comment]
in my case 0.25.3 will not run...    I try later the 0.31.2.  Did you test with spawn or fork?

**Comment by jviotti** [comment]
@rbartholomay I'm not spawning `init.js` at all manually. I believe it gets loaded by Electron by default?

**Comment by rbartholomay** [comment]
it should when i understand the docu correctly. I have a also different problem, when spawning or forking inside an asar.archive

**Comment by jviotti** [comment]
@rbartholomay Yeah, there seems to be two different issues under the same symptoms. I'll try bisecting electron later and see what I find.

**Comment by voldmar** [comment]
If this issue is still actual, I found a temporary solution: patch `node_modules/electron-winstaller/template.nuspec` so it has forward slashes instead of backslashes in paths. I suppose that problem in escaping backslashes in path strings, but old C standards tell that one should use forward slashes in paths agnostically to OS. Every other modern Windows API dealing with paths should understand forward slashes so there no need to use backslashes with possible escaping issues.
