### ISSUE TITLE
Electron Build failing on Mac after updating to 0.31

### ISSUE THREAD

**Issue by mattotodd** [atom/electron#2616]
Get this when trying to build on mac when pulling in 0.31

In file included from ../../vendor/brightray/browser/inspectable_web_contents_impl.cc:6:
../../vendor/brightray/browser/inspectable_web_contents_impl.h:147:59: error: only virtual member functions can be marked 'override'
  void WebContentsFocused(content::WebContents* contents) override;
                                                          ^~~~~~~~
../../vendor/brightray/browser/inspectable_web_contents_impl.cc:24:10: fatal error: 'content/public/browser/devtools_http_handler.h' file not found
#include "content/public/browser/devtools_http_handler.h"
         ^
2 errors generated.
ninja: build stopped: subcommand failed.

**Comment by zcbenz** [comment]
You usually need to run the `bootstrap` script again when pulling new code.
