### ISSUE TITLE
autoUpdater.checkForUpdates is not a function on Windows (when using remote)

### ISSUE THREAD

**Issue by romaincointepas** [atom/electron#4346]
On Windows only (it works on Mac), on renderer (not main):

```
remote = require('electron').remote
autoUpdater = remote.autoUpdater

[...]

autoUpdater.checkForUpdates()
```

I get `autoUpdater.checkForUpdates is not a function` (it's undefined). *(Note: autoUpdater.setFeedURL() works)*

**Comment by felicienfrancois** [comment]
```
autoUpdater = remote.require('autoUpdater')
```

**Comment by romaincointepas** [comment]
@felicienfrancois I'm pretty sure it's `remote.autoUpdater` (see https://github.com/atom/electron/blob/master/docs/api/remote.md#remote). Also, it works on Mac.

**Comment by felicienfrancois** [comment]
@romaincointepas you're right, sorry for the too quick answer.

**Comment by kevinsawicki** [comment]
This was caused by #4121 and is related to #4066 

Working on a fix now, thanks for reporting this.
