### ISSUE TITLE
Uncaught Error: Cannot find module 'cheerio'

### ISSUE THREAD

**Issue by wildfiremedia** [atom/electron#3541]
On the latest Electron 0.35.x on Mac OS X 11.10.x, I tried to install npm install cheerio and get an error. It works on last tested 0.30.x. module.js:338 could be refer to module bug?

**Comment by zcbenz** [comment]
You have to install the module inside your app, recent Electron versions do not load modules from outside your app and do not recognize the `NODE_PATH` environment variable anymore.
