### ISSUE TITLE
Loading pepper plugins and EME support via CDMs

### ISSUE THREAD

**Issue by simongregory** [atom/electron#2085]
Is there an aim for Electron to support the loading of generic pepper plugins in the future? I'm asking as I'd like to understand the chances of getting a fork that achieves this (or part of it) merged into master.

Specifically my goal is to support [EMEs](https://w3c.github.io/encrypted-media/) and allow pepper plugin based [CDMs](https://w3c.github.io/encrypted-media/#definitions) load in a `<webview>`.

Trouble is I have a naive understanding of how Electron and Chromium work together. Looking at how the Pepper Flash Player was integrated then generic support appears to be easier. It should require exetending Electrons switches to recognise and proxy `--register-pepper-plugins`, there isn't any code needed to handle plugin versions.

Starting with a build of Chromium 45 I can get encrypted Widevine media playing back by using the  switch `--register-pepper-plugins="widevinecdmadapter.plugin;application/x-ppapi-widevine-cdm"`. This suggests that once versions align (I think it can be done with m44) then it's possible to experiment in Electron.

The above is pretty specific, so I'd be glad to hear about anything I've missed that might trip this up. Or if it sounds like I'm on the right track then any pointers (aside from the Flash implementation) would be valuable.

**Comment by deepak1556** [comment]
`register-pepper-plugins` need not be proxied, its already handled by the content layer of [chromium](https://code.google.com/p/chromium/codesearch#chromium/src/content/common/pepper_plugin_list.cc&sq=package:chromium&l=144&rcl=1435750164) and the ppapi binary interfaces are already present in `Electron`. So there should be no problem loading trusted plugins. I didnt try loading complex plugins, just a few from `nacl_sdk` examples.

**Comment by deepak1556** [comment]
There is some ground work left on `Electron` to get widevine work successfully, we need to override `ContentRendererClient::AddKeySystems` which registers the key systems used to select appropriate cdm. You can check `ChromeContentRendererClient::AddKeySystems` for [usage](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/renderer/chrome_content_renderer_client.cc&sq=package:chromium&rcl=1436052378&l=1501)

**Comment by simongregory** [comment]
Thanks @deepak1556 that really helps. This is my first attempt at working with a c/c++ based project so progress is slow.

I'd taken the [list of supported Chrome command line switches](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md) as exlusive. I now understand that they're not and that any switches under [content](https://code.google.com/p/chromium/codesearch#chromium/src/content/) should also be available.

I will start experimenting in `AtomRendererClient` with the code from `ChromeContentRendererClient::AddKeySystems` and see where I get to as this should be testable with the widevine plugin that is distributed with Chrome 43.

**Comment by rewiredpictures** [comment]
@simongregory any update on this? I as well am interested in using Widevine (and potentially other pepper based EME key systems). Let me know if there is anything I can help out with.

**Comment by Thrilleratplay** [comment]
I too am curious about the state of this.  The hope is Electron could provide a base to create a portable and customizable base for streaming Netflix.  I am disappointed with the limited options avaialbe for my Arch Linux based Kodi HTPC.

**Comment by simongregory** [comment]
I have tried introducing the `AddKeySystems` code from Chrome that @deepak1556 mentioned. Found it really slow as I don't know enough C. Likely to be September until I've the time to take another look - but it's still on my backlog.

**Comment by eth0lo** [comment]
Have you ever tried the instead of the pepper-plugin using the [chromium-widevine](http://www.slackware.com/~alien/slackbuilds/chromium-widevine-plugin/) one?

**Comment by FWeinb** [comment]
CEF added support for this here https://bitbucket.org/chromiumembedded/cef/commits/b97781424875fcde970c1a2b440acecc86683ad3 just as a starting point if anyone wants to take this.

**Comment by simongregory** [comment]
Thanks @FWeinb that change set is really helpful. Progress wise this has been picked up again and is slowly moving forward.

**Comment by romaincointepas** [comment]
@simongregory Have you made any interesting progress?

**Comment by romaincointepas** [comment]
@simongregory Ok awesome! Any chance you could comment on this thread when you have the update mechanism working?

On a related note, anything that would make your branches un-mergeable with the main electron/brightray repos?

**Comment by FWeinb** [comment]
Will this work on arm devices like the raspberry pi or is there something else needed to get that working there.

**Comment by simongregory** [comment]
@romaincointepas Sure, I'll link the PR. In terms of merging I'm expecting some discussion on the implementation (i.e. making sure it's inline with Electron conventions), and to go over any licensing issues that may be relevant regarding proprietary codecs and Widevine.

@FWeinb it's not something I've looked into yet, I hope it does - assuming it's possible to find compatible widevine plugins.

**Comment by romaincointepas** [comment]
@simongregory @deepak1556 As this is the missing piece for my project, I've added a $100 bounty to this (widevine support for Mac/Win): https://www.bountysource.com/issues/23320402-loading-pepper-plugins-and-eme-support-via-cdms.

Also, I would love to give a hand during testing but this is way too low-level for me to help.

**Comment by clebeaupin** [comment]
I have tested simongregory branches of electron and libchromium projects and with some minor changes and a lot of patience, it works for me on Linux.

The first thing todo before submitting a pull request on electron is to submit 2 pull requests on brightray and libchromium.

As Simon told us and because of licence issues, I am not sure that these pull requests will be merged.
It would be great if the lead developer of these projects could answer to the licence question

**Comment by romaincointepas** [comment]
@simongregory I have merged your 2 forks with `atom/electron` and `atom/libchromiumcontent` recent masters (I needed to get the recent Xcode 7 fixes), it's all here:
https://github.com/romaincointepas/electron
https://github.com/romaincointepas/brightray
https://github.com/romaincointepas/libchromiumcontent/tree/atom
*Note: I've updated the relevant submodules in electron and brightray to point to the respective forks*

When building electron I'm getting a lot of C++ errors like those:
```
../../chromium_src/chrome/renderer/media/chrome_key_systems.cc:55:3: error: expected expression
  return is_available;
  ^
../../chromium_src/chrome/renderer/media/chrome_key_systems.cc:178:2: error: expected '}'
}
 ^
../../chromium_src/chrome/renderer/media/chrome_key_systems.cc:40:59: note: to match this '{'
    std::vector<base::string16>* additional_param_values) {
```
*Potential culprit: https://github.com/atom/brightray/pull/151?*

And also, neither `GOOGLE_CHROME_BUILD` nor `CHROMIUM_BUILD` are defined so the error is thrown and `PRODUCT_STRING` never gets defined in https://github.com/simongregory/electron/blob/widevine-cdm/chromium_src/chrome/common/chrome_constants.cc#L13-L19

Any suggestions on how to fix this?

**Comment by massimopalmieri** [comment]
@romaincointepas any progress? I'm also trying to build electron and I'm getting the same errors.

**Comment by romaincointepas** [comment]
@massimopalmieri it works for me now, try with my forks (i've pushed to electron/master).

**Comment by massimopalmieri** [comment]
@romaincointepas I'm trying with your fork, now I'm getting this error

```
ninja: Entering directory `out/D'
[1/15] SOLINK "Electron Framework.framewor...Versions/A/Electron Framework", POSTBUILDS
FAILED: ../../vendor/llvm-build/Release+Asserts/bin/clang++ -shared -ObjC -stdlib=libc++ -mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -arch x86_64 -L. -install_name @rpath/Electron\ Framework.framework/Electron\ Framework -Wl,-rpath,@loader_path/Libraries -F/Users/massimo/electron/external_binaries -o "Electron Framework.framework/Versions/A/Electron Framework" @Electron_Framework.framework.rsp
clang: error: no such file or directory: '/Users/massimo/electron/vendor/brightray/vendor/download/libchromiumcontent/shared_library/libcdm_renderer.a'
clang: error: no such file or directory: '/Users/massimo/electron/vendor/brightray/vendor/download/libchromiumcontent/shared_library/libcomponent_updater.a'
ninja: build stopped: subcommand failed.
```

**Comment by romaincointepas** [comment]
@massimopalmieri I think you didn't build the atom branch of libchromiumcontent?

**Comment by clebeaupin** [comment]
@romaincointepas Have you planned to submit a pull request on libchromiumcontent, brightray and finally on electron ?

**Comment by romaincointepas** [comment]
@clebeaupin I only merged @simongregory's branches with master and fixed a weird error, and I will try to keep my forks up to date, but I didn't add anything.

Please read https://github.com/atom/electron/issues/2085#issuecomment-150531415 for more info.

**Comment by massimopalmieri** [comment]
@romaincointepas you're right, I wasn't compiling the right branch of libchromiumcontent. Once I compiled it I run ```./script/create-dist``` and then in electron I run ```./script/bootstrap.py -v -u file:///path-to/libchromiumcontent.zip``` but I get errors like this:
```
../../chromium_src/chrome/common/chrome_paths.cc:35:10: fatal error: 'third_party/widevine/cdm/stub/widevine_cdm_version.h' file not found
#include "third_party/widevine/cdm/stub/widevine_cdm_version.h"
```

**Comment by rewiredpictures** [comment]
@romaincointepas I just pulled your branch and got it to build, but it doesn't look widevine playback is working. 

These are the steps I followed to do the build:

    # checkout the electron branch w/ EME support
    git clone --recursive git@github.com:romaincointepas/electron.git

    # build libchromiumcontent
    cd electron/vendor/brightray/vendor/libchromiumcontent
    ./script/bootstrap -v
    ./script/update -t x64
    ./script/build -t x64
    ./script/create-dist

    # move libchromiumcontent zips to the right spot
    mkdir -p osx/x64/464aff2398f619b1d4d91b9187de69803919dca2
    cp libchromiumcontent.zip osx/x64/464aff2398f619b1d4d91b9187de69803919dca2/
    cp libchromiumcontent-static.zip osx/x64/464aff2398f619b1d4d91b9187de69803919dca2
    cd ../../../../

    # add the widevinecdmadpater
    cp ~/Library/Application\ Support/Google/Chrome/WidevineCDM/1.4.8.824/_platform_specific/mac_x64/widevinecdmadapter.plugin vendor/brightray/vendor/download/libchromiumcontent/shared_library

    # trigger the build
    ./script/bootstrap.py -v -u file://`pwd`/vendor/brightray/vendor/libchromiumcontent
    ./script/build.py -c D


Here's how i'm testing for widevine support:

     var video = document.createElement('video');
     video.canPlayType('video/mp4; codecs="avc1.640028', 'com.widevine.alpha');
    // returns "" on electron, chrome it returns "probably"

Please let me know what i'm missing. Thanks for effort, I'm super excited to get this working!

**Comment by romaincointepas** [comment]
Again, it's @simongregory and @natgolov's work, I just happen to be less busy.

@massimopalmieri Follow @rewiredpictures step called `# add the widevinecdmadpater` before building, the follow instructions below.

@rewiredpictures I've copied both `widevinecdmadapter.plugin` and `libwidevinecdm.dylib` from the Google `Application Support/` location to a `plugins' folder in my app, then in main.js I added:

```
widevine_adapter_path = path.join __dirname, '../plugins/widevinecdmadapter.plugin'
app.commandLine.appendSwitch 'register-pepper-plugins', "#{widevine_adapter_path};application/x-ppapi-widevine-cdm"
```

Also, don't forget to add `plugins: true` to the `BrowserWindow` or the `plugins` attribute to the `webview` when necessary.

You easily can check if the plugin is loaded by typing `navigator.plugins` in the dev tools console.

**Comment by massimopalmieri** [comment]
thanks @romaincointepas, that worked

**Comment by massimopalmieri** [comment]
@rewiredpictures try with ```navigator.requestMediaKeySystemAccess('com.widevine.alpha', [{contentType: 'video/mp4; codecs="avc1.4d401e"'}])``` to test for widevine support, ```canPlayType``` was deprecated

**Comment by massimopalmieri** [comment]
has anyone tried to use shaka player after enabling widevine?

**Comment by simongregory** [comment]
Although I did highlight I got this working on an edited version of the Electron branch sorry they didn't compile out of the box. For clarity I've [detailed the steps  I used to build electron and the upstream projects](https://gist.github.com/simongregory/0ece919708962c8432ac).

@clebeaupin glad to hear it's working on Linux.

@romaincointepas I'm working for the BBC on this, them adding extra funding via bountysource is unlikely but I've floated the idea. Good to hear that it's still working with the most recent changes from master.

@massimopalmieri yes I've tested using the [Shaka reference player](https://shaka-player-demo.appspot.com/) and it worked both with the Widevine test manifests and some custom content I have access to.

To test playback I've been using the following in `main.js` (interesting that @romaincointepas has been successful using the `register-pepper-plugins` switch).

```
//You need to manually source the widevinecdmadapter.plugin and add to the dir below
var widevinePath = app.getPath('appData').concat('/YOUR-APP-NAME/WidevineCDM/widevinecdmadapter.plugin');
app.commandLine.appendSwitch('widevine-cdm-path', widevinePath);
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.824');
```
And then one of the following in the html:

```<webview id="netflix" src="http://netflix.co.uk" plugins></webview>```

```<webview id="shaka" src="https://shaka-player-demo.appspot.com/" plugins disablewebsecurity>
</webview>```

**Comment by romaincointepas** [comment]
@simongregory Does the same *trick* work on Windows? (load `widevinecdmadapter.dll` and `widevinecdm.dll` directly, same as what works for Mac right now)

**Comment by clebeaupin** [comment]
@romaincointepas I am trying to compile a windows version and I have added these 2 dlls. I will tell you if the compilation works

**Comment by massimopalmieri** [comment]
@simongregory good to hear that shaka player worked for you, the plugin doesn't get loaded for me if I use the ```widevine-cdm-path``` switch, but it's loaded if I use the ```register-pepper-plugins``` switch as suggested by @romaincointepas.

When the plugin is loaded I can play content on Netflix and [BitDash](http://www.dash-player.com/demo/drm-test-area/), but not on the Shaka reference player, it returns: 
```
DOMException: None of the requested configurations were supported.
```

**Comment by massimopalmieri** [comment]
@romaincointepas did you compile libchromiumcontent on El capitan? I was able to compile it on OSX 10.10.1 and Xcode 6.1.1, but I get errors when trying to compile on OS X 10.11.1 with Xcode 7.1.1

**Comment by romaincointepas** [comment]
@massimopalmieri Compile with Xcode 6.4 and it will work. As soon as electron switches to Chrome 46+ you will be able to build with Xcode 7.

**Comment by rewiredpictures** [comment]
@simongregory I've tried to get a working build by following the steps you posted in your gist, but the electron build itself is throwing an error:

```
In file included from ../../atom/app/atom_content_client.cc:16:
../../chromium_src/chrome/browser/component_updater/chrome_component_updater_configurator.h:9:10: fatal error: 'components/update_client/configurator.h' file not found
```

It looks like `chrome_component_updater_configurator.h` is in the libchromiumcontent working directory, but doesn't make it over to the electron working directory after it extracts the libchromiumcontent zips. Anyone have any ideas of what's going on?

**Comment by simongregory** [comment]
@rewiredpictures did you [modify brightray.gyp](https://gist.github.com/simongregory/0ece919708962c8432ac#file-build-electron-projects-sh-L81)? I'd imagine `components/update_client/configurator.h` is from `libcomponent_updater.a`, but that's only a vaguely educated guess.

**Comment by soualid** [comment]
I managed to build the custom libchromium and electron described here, the library is loaded well by electron at startup (got a `dyld: Library not loaded: @loader_path/libwidevinecdm.dylib` if I try to remove it from my library path), but I do not manage to load the plugin at startup (ie. `navigator.plugins.length` equals `0` and `navigator.requestMediaKeySystemAccess('com.widevine.alpha', [{contentType: 'video/mp4; codecs="avc1.4d401e"'}]);` throws a `Unsupported keySystem` exception).

I tried : 
```app.commandLine.appendSwitch('widevine-cdm-path', widevine_adapter_path);
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.866');
```

and :
```app.commandLine.appendSwitch('register-pepper-plugins', widevine_adapter_path);
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.866');```

Any idea of what I am missing ? Many thanks in advance !

**Comment by zcbenz** [comment]
Widevine CDM support is now implemented on master branch and will be included in v0.36.3.

**Comment by romaincointepas** [comment]
Super awesome! Thanks @zcbenz

**Comment by tommoor** [comment]
Using Electron 0.36.3 I've followed all of the above and not been able to get the component to be detected by Netflix unfortunately... 

Webvine is showing in navigator.plugins
Running `navigator.requestMediaKeySystemAccess('com.widevine.alpha', [{contentType: 'video/mp4; codecs="avc1.4d401e"'}])` also seems to return a correct promise

@simongregory does your code from November work on todays release? Cheers!

**Comment by simongregory** [comment]
@tommoor which platform are you on? I compiled Electron on the Mac shortly after this was merged into master and it's been working for me. I hadn't got around to building it on the other platforms.

If you've followed the above, and loaded the CDM via a standard 'register-pepper-plugins' then you won't have triggered the Key registration. To do this use 'widevine-cdm-path' ('widevine-cdm-version' is also needed but you can set it to anything from my testing).

That's detailed in the [using-widevine-cdm-plugin.md](https://github.com/atom/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md) docs.

**Comment by tommoor** [comment]
On Mac here too, I've followed all of the various methods from above and have the correct files in place. The plugin *appears* to be picked up by Electron but Netflix won't use it - perhaps Netflix is looking for something else... could be doing some sort of browser / feature sniffing I'm not aware of..

**Comment by FWeinb** [comment]
Just tried the new release on OS X 10.11.2 and can successfully watch movies on Amazon Prime. 
This is the code I am using:

```js
'use strict';

const electron = require('electron');
const path = require('path');

electron.app.commandLine.appendSwitch('widevine-cdm-path', path.join(__dirname, 'widevinecdmadapter.plugin'));
electron.app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.866');

let mainWindow = null;

electron.app.on('ready', () => {
	mainWindow = new electron.BrowserWindow({
		webPreferences: {
			plugins: true
		}
	});
	mainWindow.loadUrl('https://amazon.de');
});
```

**Comment by simongregory** [comment]
I've now tried the Electron release binary on OS X 10.11.2 (verified with Shaka Player) and 10.9.5 (verified with Ep1 Series1 of Breaking Bad on Netflix UK and Shaka) without issue.  

That's using a Widevine CDM Adapter versioned at 47.0.2526.106 and a WidevineCDM versioned at 1.4.8.866.  Compatibility is maintained to 3 prior versions of Chrome (there's a manifest.json file bundled with the Widevine binaries that'll give you the oldest version exactly) so that's unlikely to be the issue.

The code I'm using isn't different in any meaningful way to @FWeinb's.  

When Netflix fails it usually does so with an error id that quickly resolves to a Widevine upgrade/install issue via a google search.

Are things any better with the WV playlists on the Shaka Player demo: https://shaka-player-demo.appspot.com/

**Comment by tommoor** [comment]
So strange, I just copy and pasted your code @FWeinb just to be 100% sure - changed the URL to the shaka-player-demo, still no luck:

![image](https://cloud.githubusercontent.com/assets/380914/12199510/84c1eba2-b610-11e5-9109-0da088dead8e.png)

Hmph. I copied the files from chrome into the application directory, I checked their permissions and everything seems good there too. hmph.

**Comment by tommoor** [comment]
One last thought, I wonder if it's because I took the plugin and lib from my Chrome version 49, and the current version in Electron is 47. Any chance you could upload those somewhere @simongregory or let me know how you got the exact version number from the `.plugin` file?

**Comment by maxmechanic** [comment]
In instances where Shaka is expected to be global, I had to include `nodeIntegration: false` in the `webPreferences` hash when instantiating the BrowserWindow. In that case, seems to be checking for the existence of things like `require`, which are on the window in Electron.

**Comment by Kylia669** [comment]
still gettin issue with netflix all plugins included widevine - also present, but netflix return 3003 error  without any description, any suggestions?

**Comment by timofonic** [comment]
Are there a win64 build for dummies? :)

**Comment by shinriyo** [comment]
Netfix can't work on Electron 

```
electron . --widevine-cdm-path /Applications/Google\ Chrome.app/Contents/Versions/56.0.2924.87/Google\ Chrome\ Framework.framework/Libraries/WidevineCdm/_platform_specific/mac_x64/widevinecdmadapter.plugin  --widevine-cdm-version 1.4.8.962
/Users/shinriyo/electron_apps/lithium/widevine/1.4.8.866/_platform_specific/mac_x64/widevinecdmadapter.plugin
```

```
const path = require('path');

let widevineVersion = '1.4.8.866';
let baseWidevinePath = './widevine/' + widevineVersion + '/_platform_specific/';
var widevine_adapter_path = '';

switch (process.platform) {
    case "win32":
        widevine_adapter_path = baseWidevinePath + process.platform + "/" + process.arch + '/widevinecdmadapter.dll';
        break;
    default:
        widevine_adapter_path = baseWidevinePath + 'mac_x64/widevinecdmadapter.plugin';
        break
}

app.commandLine.appendSwitch('widevine-cdm-path', path.join(__dirname, widevine_adapter_path));
app.commandLine.appendSwitch('widevine-cdm-version', widevineVersion);
console.log(path.join(__dirname, widevine_adapter_path));

app.on('ready', function() {
    mainWindow = new BrowserWindow({
        width: 1000,
        height: 600,
        backgroundColor: '#000000',
        'plugins': true,
        'webPreferences': {
            'plugins': true,
            'web-security': false,
            ' webaudio': true,
            'extra-plugin-dirs': [__dirname + '/plugins'],
        }
    });
```

**Comment by simongregory** [comment]
@shinriyo I can play Netflix content ok with Widevine plugin version 1.4.8.903 in Electron v1.6.0 beta. Which version of Electron are you using? It may be that your version of Electron/Chromium isn't close enough version wise to latest Widevine plugin.

**Comment by shinriyo** [comment]
@simongregory 
My Electon of `package.json` is `1.2.5`. I will try 1.6.0.

```
   "devDependencies": {
         "electron-window-manager": "^1.1.0",
         "electron-prebuilt": "^1.2.5",
         "os-locale": "^1.4.0"
     },
```

**Comment by shinriyo** [comment]
I replaced `"electron-prebuilt": "^1.2.5"` to `"electron": "^1.6.1"`.
However, not worked for me.
I don't know what is different with `-prebuilt` and without it....

I will try `Widevine plugin version 1.4.8.903` again.

**Comment by shinriyo** [comment]
Mine is `1.4.8.962`. so I replaced `1.4.8.962` plugin but not work...

**Comment by baconface** [comment]
Both `electron` and `electron-prebuilt` are the same package. You should use `electron` as the other is deprecated and occasionally (and currently) outdated.

To use beta releases you will want to install `electron@beta` though.

**Comment by shinriyo** [comment]
@baconface 
Thank you for replying.
I installed via `npm install electron@beta --save-dev.`.

however, not work yet..
https://github.com/shinriyo/lithium

**Comment by pujari28081984** [comment]
Can any one help me integrating the OCDM ( https://github.com/fraunhoferfokus/open-content-decryption-module) in chromium browser. I tried building the compatible chromium browser ( V43.0.2357.81) but the chromium build itself is failing .

I want some demo on how OCDM + CDMi works along with browser 

Any suggestion on the above will really be helpful.

Thanks
Pujari
