### PR TITLE
Don't use ES6 class for auto updater

### LINKED ISSUE #4346: autoUpdater.checkForUpdates is not a function on Windows (when using remote)
On Windows only (it works on Mac), on renderer (not main):

```
remote = require('electron').remote
autoUpdater = remote.autoUpdater

[...]

autoUpdater.checkForUpdates()
```

I get `autoUpdater.checkForUpdates is not a function` (it's undefined). *(Note: autoUpdater.setFeedURL() works)*

### PR DESCRIPTION
**Pull request by kevinsawicki**
Don't use an ES6 class for the `AutoUpdater` class on Windows due to #4066 

This was a regression introduced in #4121 

This pull request also adds some initial specs for the `autoUpdater` to prevent future regressions like this.

Here is a pic of it now working on Windows 10:

screen shot 2016-02-03 at 10 46 07 am

Fixes #4346

### CODE REVIEW

**Comment by KevinMartin** [comment]
Since ES6+ is the way of the future, I don't see this as a future-friendly PR.

You can easily enumerate through Classes prototype methods, just not through regular for-loops or `Object.keys()`.

Wouldn't it just be better to modify `remote.js` or whatever to properly enumerate through the class methods?

```
const props = Object.getOwnPropertyNames(Object.getPrototypeOf(classInstance));

for (let name of props) {
    let method = callbacks[name];
}
```

**Comment by kevinsawicki** [comment]
> Wouldn't it just be better to modify remote.js or whatever to properly enumerate through the class methods?

Since this was a regression I was hoping to get out a quick release with this fix in it.

Then we can decide how to fix #4066 correctly, add more testing in that area, and then port this class back over, it is very small and should be quite simple to get back to ES6.

**Comment by kevinsawicki** [comment]
@zcbenz are you okay with the fix here or would you prefer more generally fixing the remote module problem with ES6 classes?
