### ISSUE TITLE
--debug-brk doesn't work

### ISSUE THREAD

**Issue by MikeGCV** [atom/electron#2335]
I'm trying to debug with node-inspector the main process with --debug. The connection is made and the scripts are shown. The problem is with --debug-brk, it seems that the program  doesn't stop at first line. I don't know if i'm doing something wrong

Thank you

**Comment by wyattbiker** [comment]
I am having the exact same issue. What seems to be the problem is that the inspector cannot find the following path on my Mac:

Error: Cannot find module '
/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.0/node-v44-darwin-x64/debug.node'

Few other people already reporting this issue elsewhere. It seems node-inspector is getting confused which debug.node to use.

**Comment by lminds** [comment]
the same problem  in node module sqllite3:
```
Uncaught Error: Cannot find module 'D:\workspace\electron\sample1\node_modules\sqlite3\lib\binding\node-v44-win32-x64\node_sqlite3.node'
```
if find it  the process.versions.modules is different between nodejs and electron

nodejs:
```
> process.versions.modules
'14'
```
electron-v0.30.0-win32-x64:
```
> process.versions.modules
"44"
```

**Comment by shrewdlogarithm** [comment]
Not sure if this is related, but using the latest version of Node-inspector (installed today) doesn't seem to work with electron (0.30.4 and some earlier builds tried) AT ALL 

I following the wiki (little of it which there is) - no joy with ANYTHING

--debug-brk doesn't do anything at all

--debug doesn't work either 

I either case no breakpoints are hit and no code is available in the connected devtools window (Chrome) 

No error messages I don't get WITHOUT --debug flags either - so I'm lost (and about to give-up on Electron because not being able to debug code is frustrating-as-hell)

Using (Windows 7-64 bit versonm

**Comment by apexskier** [comment]
I'm in the same position as @shrewdlogarithm I think, but on OS X 10.10.5. Running my app with either the --debug-brk or --debug flag doesn't do anything, no app opening, no activity in the debugger, no error messages. Without flags, the app opens fine.

**Comment by shrewdlogarithm** [comment]
As of 0.30.6, if I start node-inspector, then open the debug page in Chrome
(http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858) then run my app with
--debug=5858, the app says "Debugger listening on port 5858" but NOTHING
else happens, the app does not run.

If you reload the Chrome debug page whilst it's sitting doing nothing, you
get this error

E:\dropbox\~work\webstorm\usl\livedeploy\windows>electron --debug=5858

E:\dropbox\~work\webstorm\usl\livedeploy\windows>Debugger listening on port
5858

events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TCP.onread (net.js:541:26)


Not sure if that's related or not???
